# Generated by Django 5.2.1 on 2025-05-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbodiedImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_footprint', models.FloatField(blank=True, null=True, verbose_name='Carbon footprint (gCO2e)')),
                ('carbon_footprint_source', models.CharField(blank=True, max_length=255, verbose_name='Source and method (carbon footprint)')),
                ('depletion_abiotic', models.FloatField(blank=True, null=True, verbose_name='Depletion of Abiotic Resources (kg Sb-eq)')),
                ('depletion_abiotic_source', models.CharField(blank=True, max_length=255, verbose_name='Source and method (depletion)')),
                ('particulate_matter', models.FloatField(blank=True, null=True, verbose_name='Particulate Matter Emissions (disease incidence)')),
                ('particulate_matter_source', models.CharField(blank=True, max_length=255, verbose_name='Source and method (particulate matter)')),
                ('acidification_potential', models.FloatField(blank=True, null=True, verbose_name='Acidification potential (kg mol H+)')),
                ('acidification_potential_source', models.CharField(blank=True, max_length=255, verbose_name='Source and method (acidification)')),
                ('ionising_radiation', models.FloatField(blank=True, null=True, verbose_name='Ionising Radiation (kBq U-235)')),
                ('ionising_radiation_source', models.CharField(blank=True, max_length=255, verbose_name='Source and method (ionising radiation)')),
                ('photochemical_ozone', models.FloatField(blank=True, null=True, verbose_name='Photochemical Ozone Formation (kg NMVOC-eq)')),
                ('photochemical_ozone_source', models.CharField(blank=True, max_length=255, verbose_name='Source and method (ozone)')),
                ('abiotic_depletion_fossil', models.FloatField(blank=True, null=True, verbose_name='Abiotic Depletion Potential (MJ)')),
                ('abiotic_depletion_fossil_source', models.CharField(blank=True, max_length=255, verbose_name='Source and method (fossil fuels)')),
                ('freshwater_ecotoxicity', models.FloatField(blank=True, null=True, verbose_name='Freshwater Eco-Toxicity Potential (CTUe)')),
                ('freshwater_ecotoxicity_source', models.CharField(blank=True, max_length=255, verbose_name='Source and method (ecotoxicity)')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_consumption', models.FloatField(blank=True, null=True, verbose_name='Energy consumption (kWh)')),
                ('carbon_footprint', models.FloatField(blank=True, null=True, verbose_name='Carbon footprint (gCO2e)')),
                ('water_consumption', models.FloatField(blank=True, null=True, verbose_name='Water consumption (liters)')),
            ],
        ),
    ]
