# Generated by Django 5.2.1 on 2025-05-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('keywords', models.CharField(max_length=255, verbose_name='Keywords (comma-separated)')),
                ('repository_url', models.URLField(blank=True, verbose_name='Repository URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('affiliation', models.CharField(blank=True, max_length=255, verbose_name='Affiliation')),
                ('orcid', models.CharField(blank=True, max_length=19, verbose_name='ORCID')),
                ('is_corresponding', models.BooleanField(default=False, verbose_name='Corresponding Author')),
                ('order', models.PositiveIntegerField(default=0)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='interface.basicinformation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
